services:
  - type: web
    name: endee-vector-db
    runtime: image
    plan: free
    image:
      url: docker.io/endeeio/endee-server:latest
    healthCheckPath: /api/v1/health
    envVars:
      - key: PORT
        value: "8080"
      - key: NDD_SERVER_PORT
        value: "8080"
      - key: NDD_DATA_DIR
        value: /tmp/endee-data
      - key: NDD_NUM_THREADS
        value: "0"

  - type: web
    name: project-rag-app
    runtime: python
    plan: free
    rootDir: project-RAG
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT --server.headless true
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: INDEX_NAME
        value: RAGSYS
      - key: ENDEE_HOSTPORT
        fromService:
          type: web
          name: endee-vector-db
          property: hostport
      - key: GROQ_API_KEY
        sync: false
